import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Download, FilePlus2, Plus, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { addQuoteItem, addQuoteService, createInvoiceFromQuote, deleteQuoteItem, updateQuote } from "@/lib/actions/business";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CommercialStatusBadge } from "@/components/commercial-status-badge";
import { EntityReference } from "@/components/entity-reference";
import { EmptyState } from "@/components/empty-state";
import { formatBusinessDate, formatMoney, humanise, quoteStatuses } from "@/lib/business";
import { ServicePickerForm } from "@/components/business/service-picker-form";

export default async function QuotePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient();
  const { data: quote } = await supabase.from("quotes").select("*, organisations(name, client_reference), events(name, event_reference), quote_items(*)").eq("id", id).maybeSingle();
  if (!quote) notFound();
  const { data: services } = await supabase.from("business_services").select("id, code, name, category, default_unit_price, unit_label").eq("active", true).order("category").order("name");
  const org = quote.organisations as { name: string; client_reference: string } | null; const event = quote.events as { name: string; event_reference: string } | null;
  const items = [...quote.quote_items].sort((a, b) => a.position - b.position);
  return <div className="mx-auto max-w-6xl"><Link href="/business" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-tide-charcoal"><ArrowLeft className="size-4" />Business</Link><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><div className="mb-3 flex flex-wrap gap-1.5"><EntityReference label="Quote ID" value={quote.quote_reference} /><EntityReference label="Client ID" value={org?.client_reference} />{event && <EntityReference label="Event ID" value={event.event_reference} />}</div><h1 className="text-3xl font-semibold tracking-tight text-tide-charcoal">{quote.title}</h1><p className="mt-2 text-sm text-muted-foreground">{org?.name} · Issued {formatBusinessDate(quote.issue_date)} · Valid until {formatBusinessDate(quote.valid_until)}</p></div><div className="flex flex-wrap items-center gap-2"><CommercialStatusBadge status={quote.status} /><Button render={<Link href={`/api/business/quote/${quote.id}/pdf`} />} nativeButton={false} size="sm" variant="outline"><Download />Download PDF</Button><form action={createInvoiceFromQuote}><input type="hidden" name="quote_id" value={quote.id} /><Button type="submit" size="sm" variant="outline"><FilePlus2 />Create invoice</Button></form></div></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><Card className="gap-0 py-0"><CardHeader className="border-b py-4"><CardTitle>Quote lines</CardTitle></CardHeader><CardContent className="p-0">{items.length ? <Table><TableHeader><TableRow><TableHead>Description</TableHead><TableHead className="text-right">Qty</TableHead><TableHead className="text-right">Unit</TableHead><TableHead className="text-right">VAT</TableHead><TableHead className="text-right">Total</TableHead><TableHead /></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.description}</TableCell><TableCell className="text-right tabular-nums">{item.quantity}</TableCell><TableCell className="text-right tabular-nums">{formatMoney(item.unit_price)}</TableCell><TableCell className="text-right tabular-nums">{item.tax_rate}%</TableCell><TableCell className="text-right font-semibold tabular-nums">{formatMoney(Number(item.quantity) * Number(item.unit_price) * (1 + Number(item.tax_rate) / 100))}</TableCell><TableCell className="text-right"><form action={deleteQuoteItem}><input type="hidden" name="quote_id" value={quote.id} /><input type="hidden" name="item_id" value={item.id} /><Button type="submit" size="icon-sm" variant="ghost" aria-label="Delete quote line"><Trash2 /></Button></form></TableCell></TableRow>)}</TableBody></Table> : <EmptyState icon={Plus} title="No quote lines yet" description="Add the services, quantities and pricing below." className="border-none py-10" />}</CardContent><div className="border-t bg-[#f8f9f9] px-5 py-4"><form action={addQuoteItem} className="grid gap-3 md:grid-cols-[1fr_90px_130px_90px_auto]"><input type="hidden" name="quote_id" value={quote.id} /><input type="hidden" name="position" value={items.length + 1} /><Input name="description" required placeholder="Service or deliverable" aria-label="Description" /><Input name="quantity" required type="number" min="0.01" step="0.01" defaultValue="1" aria-label="Quantity" /><Input name="unit_price" required type="number" min="0" step="0.01" placeholder="Unit price" aria-label="Unit price" /><Input name="tax_rate" required type="number" min="0" max="100" step="0.01" defaultValue="20" aria-label="VAT rate" /><Button type="submit"><Plus />Add</Button></form></div></Card>
      <ServicePickerForm action={addQuoteService} parentName="quote_id" parentId={quote.id} services={services ?? []} />
      <Card><CardHeader className="border-b"><CardTitle>Totals</CardTitle></CardHeader><CardContent className="ml-auto max-w-sm space-y-3"><div className="flex justify-between text-sm"><span className="text-muted-foreground">Subtotal</span><strong>{formatMoney(quote.subtotal)}</strong></div><div className="flex justify-between text-sm"><span className="text-muted-foreground">VAT</span><strong>{formatMoney(quote.tax_total)}</strong></div><div className="flex justify-between border-t pt-3 text-lg"><span>Total</span><strong>{formatMoney(quote.total)}</strong></div></CardContent></Card></div>
      <Card><CardHeader className="border-b"><CardTitle>Issue and publish</CardTitle></CardHeader><CardContent><form action={updateQuote} className="space-y-4"><input type="hidden" name="id" value={quote.id} /><div className="space-y-1.5"><Label htmlFor="status">Status</Label><select id="status" name="status" defaultValue={quote.status} className="h-10 w-full rounded-lg border border-input bg-white px-3 text-sm">{quoteStatuses.map((status) => <option key={status} value={status}>{humanise(status)}</option>)}</select></div><label className="flex items-start gap-3 rounded-lg border bg-[#f8f9f9] p-3"><input type="checkbox" name="client_visible" defaultChecked={quote.client_visible} className="mt-1 size-4" /><span><strong className="block text-sm">Show in client portal</strong><small className="text-muted-foreground">The client can see this quote and all line items.</small></span></label><div className="space-y-1.5"><Label htmlFor="valid_until">Valid until</Label><Input id="valid_until" name="valid_until" type="date" defaultValue={quote.valid_until ?? ""} /></div><div className="space-y-1.5"><Label htmlFor="accepted_by_name">Accepted by</Label><Input id="accepted_by_name" name="accepted_by_name" defaultValue={quote.accepted_by_name ?? ""} /></div><div className="space-y-1.5"><Label htmlFor="notes">Notes</Label><Textarea id="notes" name="notes" rows={3} defaultValue={quote.notes ?? ""} /></div><div className="space-y-1.5"><Label htmlFor="terms">Terms</Label><Textarea id="terms" name="terms" rows={4} defaultValue={quote.terms ?? ""} /></div><Button type="submit">Save quote</Button></form></CardContent></Card></div>
  </div>;
}
