import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, FileSignature, Plus, ReceiptText } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { updateOpportunity } from "@/lib/actions/business";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { CommercialStatusBadge } from "@/components/commercial-status-badge";
import { EntityReference } from "@/components/entity-reference";
import { EmptyState } from "@/components/empty-state";
import { formatBusinessDate, formatMoney, humanise, opportunityStages } from "@/lib/business";

export default async function OpportunityPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient();
  const [{ data: item }, { data: quotes }, { data: proposals }] = await Promise.all([
    supabase.from("business_opportunities").select("*, organisations(name, client_reference), events(id, name, event_reference)").eq("id", id).maybeSingle(),
    supabase.from("quotes").select("id, quote_reference, title, status, total").eq("opportunity_id", id).order("created_at", { ascending: false }),
    supabase.from("proposals").select("id, proposal_reference, title, status").eq("opportunity_id", id).order("created_at", { ascending: false }),
  ]);
  if (!item) notFound();
  const org = item.organisations as { name: string; client_reference: string } | null;
  const event = item.events as { id: string; name: string; event_reference: string } | null;
  return <div className="mx-auto max-w-6xl"><Link href="/business" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-tide-charcoal"><ArrowLeft className="size-4" />Business</Link><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><div className="mb-3 flex flex-wrap gap-1.5"><EntityReference label="Opportunity ID" value={item.opportunity_reference} /><EntityReference label="Client ID" value={org?.client_reference} />{event && <EntityReference label="Event ID" value={event.event_reference} />}</div><h1 className="text-3xl font-semibold tracking-tight text-tide-charcoal">{item.name}</h1><p className="mt-2 text-sm text-muted-foreground">{org?.name}{event ? ` · ${event.name}` : " · Pre-event opportunity"}</p></div><CommercialStatusBadge status={item.stage} /></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><Card><CardHeader className="border-b"><CardTitle>Commercial position</CardTitle></CardHeader><CardContent className="grid grid-cols-3 gap-4"><div><p className="section-label">Estimated value</p><p className="mt-2 text-xl font-semibold">{formatMoney(item.estimated_value)}</p></div><div><p className="section-label">Probability</p><p className="mt-2 text-xl font-semibold">{item.probability}%</p></div><div><p className="section-label">Expected decision</p><p className="mt-2 font-semibold">{formatBusinessDate(item.expected_close_date)}</p></div></CardContent></Card>
      <div className="grid gap-5 md:grid-cols-2"><Card className="gap-0 py-0"><CardHeader className="flex-row items-center justify-between border-b py-4"><CardTitle className="flex items-center gap-2"><FileSignature className="size-4 text-tide-teal" />Proposals</CardTitle><Button render={<Link href="/business/proposals/new" />} nativeButton={false} size="icon-sm" variant="ghost" aria-label="New proposal"><Plus /></Button></CardHeader><CardContent className="p-0">{proposals?.length ? proposals.map((record) => <Link key={record.id} href={`/business/proposals/${record.id}`} className="flex items-center justify-between border-b px-5 py-4 last:border-0"><span><strong className="block text-sm">{record.title}</strong><small className="text-muted-foreground">{record.proposal_reference}</small></span><CommercialStatusBadge status={record.status} /></Link>) : <EmptyState icon={FileSignature} title="No proposals" className="border-none py-9" />}</CardContent></Card>
      <Card className="gap-0 py-0"><CardHeader className="flex-row items-center justify-between border-b py-4"><CardTitle className="flex items-center gap-2"><ReceiptText className="size-4 text-tide-teal" />Quotes</CardTitle><Button render={<Link href="/business/quotes/new" />} nativeButton={false} size="icon-sm" variant="ghost" aria-label="New quote"><Plus /></Button></CardHeader><CardContent className="p-0">{quotes?.length ? quotes.map((record) => <Link key={record.id} href={`/business/quotes/${record.id}`} className="flex items-center justify-between border-b px-5 py-4 last:border-0"><span><strong className="block text-sm">{record.quote_reference}</strong><small className="text-muted-foreground">{formatMoney(record.total)}</small></span><CommercialStatusBadge status={record.status} /></Link>) : <EmptyState icon={ReceiptText} title="No quotes" className="border-none py-9" />}</CardContent></Card></div></div>
      <Card><CardHeader className="border-b"><CardTitle>Manage opportunity</CardTitle></CardHeader><CardContent><form action={updateOpportunity} className="space-y-4"><input type="hidden" name="id" value={item.id} /><div className="space-y-1.5"><Label htmlFor="stage">Stage</Label><select id="stage" name="stage" defaultValue={item.stage} className="h-10 w-full rounded-lg border border-input bg-white px-3 text-sm">{opportunityStages.map((status) => <option key={status} value={status}>{humanise(status)}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div className="space-y-1.5"><Label htmlFor="estimated_value">Value</Label><Input id="estimated_value" name="estimated_value" type="number" min="0" step="0.01" defaultValue={item.estimated_value} /></div><div className="space-y-1.5"><Label htmlFor="probability">Probability</Label><Input id="probability" name="probability" type="number" min="0" max="100" defaultValue={item.probability} /></div></div><div className="space-y-1.5"><Label htmlFor="expected_close_date">Expected decision</Label><Input id="expected_close_date" name="expected_close_date" type="date" defaultValue={item.expected_close_date ?? ""} /></div><div className="space-y-1.5"><Label htmlFor="notes">Notes</Label><Textarea id="notes" name="notes" rows={5} defaultValue={item.notes ?? ""} /></div><div className="space-y-1.5"><Label htmlFor="lost_reason">Lost reason</Label><Textarea id="lost_reason" name="lost_reason" rows={2} defaultValue={item.lost_reason ?? ""} /></div><Button type="submit">Save changes</Button></form></CardContent></Card></div>
  </div>;
}
