import Link from "next/link";
import { FileSignature, Plus } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CommercialStatusBadge } from "@/components/commercial-status-badge";
import { EmptyState } from "@/components/empty-state";
import { EntityReference } from "@/components/entity-reference";
import { formatBusinessDate } from "@/lib/business";

export default async function ProposalsRegisterPage() { const supabase=await createClient(); const {data}=await supabase.from("proposals").select("*, organisations(name, client_reference), events(name, event_reference)").order("created_at",{ascending:false}); return <div className="mx-auto max-w-[1480px]"><PageHeader eyebrow="Business register" title="Proposals" description="Issued scope and approach records with client-portal publication and acceptance status." actions={<Button render={<Link href="/business/proposals/new" />} nativeButton={false}><Plus />New proposal</Button>} /><Card className="gap-0 py-0"><CardContent className="p-0">{data?.length?<Table><TableHeader><TableRow><TableHead>Proposal</TableHead><TableHead>Client / event</TableHead><TableHead>Valid until</TableHead><TableHead>Portal</TableHead><TableHead className="text-right">Status</TableHead></TableRow></TableHeader><TableBody>{data.map((record)=>{const org=record.organisations as {name:string;client_reference:string}|null; const event=record.events as {name:string;event_reference:string}|null; return <TableRow key={record.id}><TableCell><Link href={`/business/proposals/${record.id}`} className="font-semibold text-tide-charcoal hover:text-tide-teal">{record.title}</Link><EntityReference label="Proposal ID" value={record.proposal_reference} className="mt-1" /></TableCell><TableCell><span className="block">{org?.name}</span><div className="mt-1 flex gap-1"><EntityReference label="Client ID" value={org?.client_reference}/>{event&&<EntityReference label="Event ID" value={event.event_reference}/>}</div></TableCell><TableCell>{formatBusinessDate(record.valid_until)}</TableCell><TableCell>{record.client_visible?"Published":"Internal"}</TableCell><TableCell className="text-right"><CommercialStatusBadge status={record.status}/></TableCell></TableRow>})}</TableBody></Table>:<EmptyState icon={FileSignature} title="No proposals" className="border-none py-14"/>}</CardContent></Card></div> }
