import Link from "next/link";
import { Plus, ReceiptText } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CommercialStatusBadge } from "@/components/commercial-status-badge";
import { EmptyState } from "@/components/empty-state";
import { EntityReference } from "@/components/entity-reference";
import { formatBusinessDate, formatMoney } from "@/lib/business";

export default async function InvoicesRegisterPage(){const supabase=await createClient();const{data}=await supabase.from("invoices").select("*, organisations(name, client_reference), events(name, event_reference)").order("created_at",{ascending:false});const today=new Date().toISOString().slice(0,10);return <div className="mx-auto max-w-[1480px]"><PageHeader eyebrow="Finance register" title="Invoices" description="Issued value, due dates, payments and remaining balances for every client and event." actions={<Button render={<Link href="/business/invoices/new"/>} nativeButton={false}><Plus/>New invoice</Button>}/><Card className="gap-0 py-0"><CardContent className="p-0">{data?.length?<Table><TableHeader><TableRow><TableHead>Invoice</TableHead><TableHead>Client / event</TableHead><TableHead>Due</TableHead><TableHead className="text-right">Total</TableHead><TableHead className="text-right">Paid</TableHead><TableHead className="text-right">Balance</TableHead><TableHead className="text-right">Status</TableHead></TableRow></TableHeader><TableBody>{data.map((record)=>{const org=record.organisations as {name:string;client_reference:string}|null;const event=record.events as {name:string;event_reference:string}|null;const status=record.status==="sent"&&record.due_date&&record.due_date<today&&Number(record.balance_due)>0?"overdue":record.status;return <TableRow key={record.id}><TableCell><Link href={`/business/invoices/${record.id}`} className="font-semibold text-tide-charcoal hover:text-tide-teal">{record.title}</Link><EntityReference label="Invoice ID" value={record.invoice_reference} className="mt-1"/></TableCell><TableCell><span className="block">{org?.name}</span><div className="mt-1 flex gap-1"><EntityReference label="Client ID" value={org?.client_reference}/>{event&&<EntityReference label="Event ID" value={event.event_reference}/>}</div></TableCell><TableCell>{formatBusinessDate(record.due_date)}</TableCell><TableCell className="text-right font-semibold">{formatMoney(record.total)}</TableCell><TableCell className="text-right text-success">{formatMoney(record.amount_paid)}</TableCell><TableCell className="text-right font-semibold">{formatMoney(record.balance_due)}</TableCell><TableCell className="text-right"><CommercialStatusBadge status={status}/></TableCell></TableRow>})}</TableBody></Table>:<EmptyState icon={ReceiptText} title="No invoices" className="border-none py-14"/>}</CardContent></Card></div>}
