import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Banknote, Download, Plus, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { addInvoiceItem, addInvoiceService, deleteInvoiceItem, recordPayment, updateInvoice } from "@/lib/actions/business";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CommercialStatusBadge } from "@/components/commercial-status-badge";
import { EntityReference } from "@/components/entity-reference";
import { EmptyState } from "@/components/empty-state";
import { formatBusinessDate, formatMoney, humanise, invoiceStatuses } from "@/lib/business";
import { ServicePickerForm } from "@/components/business/service-picker-form";

export default async function InvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient();
  const [{ data: invoice }, { data: payments }] = await Promise.all([
    supabase.from("invoices").select("*, organisations(name, client_reference), events(name, event_reference), invoice_items(*)").eq("id", id).maybeSingle(),
    supabase.from("payments").select("*").eq("invoice_id", id).order("paid_on", { ascending: false }),
  ]);
  if (!invoice) notFound();
  const { data: services } = await supabase.from("business_services").select("id, code, name, category, default_unit_price, unit_label").eq("active", true).order("category").order("name");
  const org = invoice.organisations as { name: string; client_reference: string } | null; const event = invoice.events as { name: string; event_reference: string } | null;
  const items = [...invoice.invoice_items].sort((a, b) => a.position - b.position); const today = new Date().toISOString().slice(0, 10);
  const displayStatus = invoice.status === "sent" && invoice.due_date && invoice.due_date < today && Number(invoice.balance_due) > 0 ? "overdue" : invoice.status;
  return <div className="mx-auto max-w-6xl"><Link href="/business" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-tide-charcoal"><ArrowLeft className="size-4" />Business</Link><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><div className="mb-3 flex flex-wrap gap-1.5"><EntityReference label="Invoice ID" value={invoice.invoice_reference} /><EntityReference label="Client ID" value={org?.client_reference} />{event && <EntityReference label="Event ID" value={event.event_reference} />}</div><h1 className="text-3xl font-semibold tracking-tight text-tide-charcoal">{invoice.title}</h1><p className="mt-2 text-sm text-muted-foreground">{org?.name} · Due {formatBusinessDate(invoice.due_date)}</p></div><div className="flex flex-wrap items-center gap-2"><CommercialStatusBadge status={displayStatus} /><Button render={<Link href={`/api/business/invoice/${invoice.id}/pdf`} />} nativeButton={false} size="sm" variant="outline"><Download />Download PDF</Button></div></div>
    <div className="mb-5 grid grid-cols-2 gap-3.5 lg:grid-cols-4"><div className="rounded-xl border bg-white p-4"><p className="section-label">Invoice total</p><strong className="mt-2 block text-xl">{formatMoney(invoice.total)}</strong></div><div className="rounded-xl border bg-white p-4"><p className="section-label">Paid</p><strong className="mt-2 block text-xl text-success">{formatMoney(invoice.amount_paid)}</strong></div><div className="rounded-xl border bg-white p-4"><p className="section-label">Balance due</p><strong className="mt-2 block text-xl text-tide-charcoal">{formatMoney(invoice.balance_due)}</strong></div><div className="rounded-xl border bg-white p-4"><p className="section-label">Due date</p><strong className="mt-2 block text-lg">{formatBusinessDate(invoice.due_date)}</strong></div></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><Card className="gap-0 py-0"><CardHeader className="border-b py-4"><CardTitle>Invoice lines</CardTitle></CardHeader><CardContent className="p-0">{items.length ? <Table><TableHeader><TableRow><TableHead>Description</TableHead><TableHead className="text-right">Qty</TableHead><TableHead className="text-right">Unit</TableHead><TableHead className="text-right">VAT</TableHead><TableHead className="text-right">Total</TableHead><TableHead /></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.description}</TableCell><TableCell className="text-right">{item.quantity}</TableCell><TableCell className="text-right">{formatMoney(item.unit_price)}</TableCell><TableCell className="text-right">{item.tax_rate}%</TableCell><TableCell className="text-right font-semibold">{formatMoney(Number(item.quantity) * Number(item.unit_price) * (1 + Number(item.tax_rate) / 100))}</TableCell><TableCell><form action={deleteInvoiceItem}><input type="hidden" name="invoice_id" value={invoice.id} /><input type="hidden" name="item_id" value={item.id} /><Button type="submit" size="icon-sm" variant="ghost" aria-label="Delete invoice line"><Trash2 /></Button></form></TableCell></TableRow>)}</TableBody></Table> : <EmptyState icon={Plus} title="No invoice lines yet" className="border-none py-10" />}</CardContent><div className="border-t bg-[#f8f9f9] px-5 py-4"><form action={addInvoiceItem} className="grid gap-3 md:grid-cols-[1fr_90px_130px_90px_auto]"><input type="hidden" name="invoice_id" value={invoice.id} /><input type="hidden" name="position" value={items.length + 1} /><Input name="description" required placeholder="Charge description" aria-label="Description" /><Input name="quantity" required type="number" min="0.01" step="0.01" defaultValue="1" aria-label="Quantity" /><Input name="unit_price" required type="number" min="0" step="0.01" placeholder="Unit price" aria-label="Unit price" /><Input name="tax_rate" required type="number" min="0" max="100" step="0.01" defaultValue="20" aria-label="VAT rate" /><Button type="submit"><Plus />Add</Button></form></div></Card>
      <ServicePickerForm action={addInvoiceService} parentName="invoice_id" parentId={invoice.id} services={services ?? []} />
      <Card className="gap-0 py-0"><CardHeader className="border-b py-4"><CardTitle className="flex items-center gap-2"><Banknote className="size-4 text-tide-teal" />Payment history</CardTitle></CardHeader><CardContent className="p-0">{payments?.length ? <Table><TableHeader><TableRow><TableHead>Payment ID</TableHead><TableHead>Date</TableHead><TableHead>Method</TableHead><TableHead>External reference</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{payments.map((payment) => <TableRow key={payment.id}><TableCell className="font-semibold">{payment.payment_reference}</TableCell><TableCell>{formatBusinessDate(payment.paid_on)}</TableCell><TableCell>{humanise(payment.method)}</TableCell><TableCell>{payment.external_reference ?? "—"}</TableCell><TableCell className="text-right font-semibold text-success">{formatMoney(payment.amount)}</TableCell></TableRow>)}</TableBody></Table> : <EmptyState icon={Banknote} title="No payments recorded" className="border-none py-8" />}</CardContent></Card></div>
      <div className="space-y-5"><Card><CardHeader className="border-b"><CardTitle>Issue and publish</CardTitle></CardHeader><CardContent><form action={updateInvoice} className="space-y-4"><input type="hidden" name="id" value={invoice.id} /><div className="space-y-1.5"><Label htmlFor="status">Status</Label><select id="status" name="status" defaultValue={invoice.status} className="h-10 w-full rounded-lg border border-input bg-white px-3 text-sm">{invoiceStatuses.map((status) => <option key={status} value={status}>{humanise(status)}</option>)}</select></div><label className="flex items-start gap-3 rounded-lg border bg-[#f8f9f9] p-3"><input type="checkbox" name="client_visible" defaultChecked={invoice.client_visible} className="mt-1 size-4" /><span><strong className="block text-sm">Show in client portal</strong><small className="text-muted-foreground">The client can view the invoice and payment history.</small></span></label><div className="space-y-1.5"><Label htmlFor="due_date">Due date</Label><Input id="due_date" name="due_date" type="date" defaultValue={invoice.due_date ?? ""} /></div><div className="space-y-1.5"><Label htmlFor="payment_terms">Payment terms</Label><Textarea id="payment_terms" name="payment_terms" rows={3} defaultValue={invoice.payment_terms ?? ""} /></div><div className="space-y-1.5"><Label htmlFor="notes">Notes</Label><Textarea id="notes" name="notes" rows={3} defaultValue={invoice.notes ?? ""} /></div><Button type="submit">Save invoice</Button></form></CardContent></Card>
      <Card><CardHeader className="border-b"><CardTitle>Record payment</CardTitle></CardHeader><CardContent><form action={recordPayment} className="space-y-4"><input type="hidden" name="invoice_id" value={invoice.id} /><div className="space-y-1.5"><Label htmlFor="amount">Amount</Label><Input id="amount" name="amount" type="number" min="0.01" step="0.01" defaultValue={invoice.balance_due} required /></div><div className="space-y-1.5"><Label htmlFor="paid_on">Payment date</Label><Input id="paid_on" name="paid_on" type="date" defaultValue={today} required /></div><div className="space-y-1.5"><Label htmlFor="method">Method</Label><select id="method" name="method" className="h-10 w-full rounded-lg border border-input bg-white px-3 text-sm"><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="cash">Cash</option><option value="cheque">Cheque</option><option value="other">Other</option></select></div><div className="space-y-1.5"><Label htmlFor="external_reference">Bank / processor reference</Label><Input id="external_reference" name="external_reference" /></div><div className="space-y-1.5"><Label htmlFor="payment_notes">Notes</Label><Textarea id="payment_notes" name="notes" rows={2} /></div><Button type="submit" variant="outline">Record payment</Button></form></CardContent></Card></div></div>
  </div>;
}
